[package]
name = "toy-json-parser"
version = "0.1.0"
edition = "2024"
rust-version = "1.86.0"
description = "A toy JSON lexer and parser"
repository = "https://github.com/masaki-wk/toy-json-parser"
license = "MIT OR Apache-2.0"
keywords = [
    "json",
    "lexer",
    "parser",
]
categories = [
    "encoding",
    "parser-implementations",
]
exclude = [
    "/.github/",
]

[dev-dependencies]
anyhow = "1.0"
clap = { version = "4.6", features = ["derive"] }
criterion = { version = "0.8", features = ["html_reports"] }
paste = "1.0"
#
# Notes on dev-dependencies:
#
# - cargo-readme 3.4.0 or newer is required to generate README.md from doc comments.
#
# Notes on Rust versions:
#
# - This crate requires the Rust 2024 edition.
# - The Rust 2024 edition requires Rust 1.85.0 or newer.
# - anyhow 1.0.x requires Rust 1.68 or newer.
# - clap 4.6.x requires Rust 1.85 or newer.
# - criterion 0.8.x requires Rust 1.86 or newer.
# - paste 1.0.x requires Rust 1.31 or newer.

[[bench]]
name = "benchmark"
harness = false
