[package]
name = "toy-json-parser"
version = "0.0.2"
edition = "2024"
rust-version = "1.86.0"
description = "A toy JSON lexer and parser"
repository = "https://github.com/masaki-wk/toy-json-parser"
license = "MIT OR Apache-2.0"
keywords = [
    "json",
    "lexer",
    "parser",
]
categories = [
    "encoding",
    "parser-implementations",
]
exclude = [
    "/.github/",
]

[dev-dependencies]
anyhow = "1.0"
clap = { version = "4.6", features = ["derive"] }
criterion = { version = "0.8", features = ["html_reports"] }
paste = "1.0"
#
# Note for dev-dependencies:
#
# - This crate requires cargo-readme v3.4.0 to generate README.md from doc comments
#
# Note for rust version:
#
# - This crate requires edition 2024
# - Edition 2024 requires rust-1.85.0
# - anyhow 1.0.104 requires rust-1.68
# - clap 4.6.6 requires rust-1.85
# - criterion 0.8.2 requires rust-1.86
# - paste 1.0.15 requires rust-1.31

[[bench]]
name = "benchmark"
harness = false
