name: Check Release Pull Request

on:
  pull_request:
    branches:
      - main

env:
  PULL_REQUEST_TITLE_PREFIX: "Release "
  TAG_PREFIX: "v"

jobs:
  verify-title:
    name: Verify pull request title (release pull request)
    if: startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0  # fetch all history for all tags and branches
      - name: Check the pull request title
        run: ./.github/tools/check-release-pull-request-title.sh "$PULL_REQUEST_TITLE_PREFIX" "$TAG_PREFIX" "${{ github.event.pull_request.title }}"

  verify-publish:
    name: Verify crate can be published (release pull request)
    needs: verify-title
    if: startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Verify publishing via cargo command
        run: cargo publish --dry-run
