name: Check Pull Request

on:
  pull_request:
    branches:
      - main

env:
  RELEASE_PULL_REQUEST_TITLE_PREFIX: "Release "
  RELEASE_BRANCH_PREFIX: "release/"
  RELEASE_TAG_PREFIX: ""
  PULL_REQUEST_TITLE: ${{ github.event.pull_request.title }}
  PULL_REQUEST_SOURCE_BRANCH: ${{ github.event.pull_request.head.ref }}

jobs:
  check-pull-request-for-release:
    name: Check the release pull request
    if: startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Get the package version
        id: get_version
        run: |
          version="$(cargo metadata --format-version=1 --no-deps | jq --raw-output '.packages[0].version')"
          echo "value=${version}" >> "$GITHUB_OUTPUT"
      - name: Check the release pull request title
        run: |
          test "$PULL_REQUEST_TITLE" = "${RELEASE_PULL_REQUEST_TITLE_PREFIX}${{ steps.get_version.outputs.value }}" || {
            echo "Error: unexpected release pull request title \`${PULL_REQUEST_TITLE}\`"
            exit 1
          }
      - name: Check the release branch name
        run: |
          test "$PULL_REQUEST_SOURCE_BRANCH" = "${RELEASE_BRANCH_PREFIX}${{ steps.get_version.outputs.value }}" || {
            echo "Error: unexpected release branch name \`${PULL_REQUEST_SOURCE_BRANCH}\`"
            exit 1
          }
      - name: Check whether the release tag already exists
        run: |
          target_tag="${RELEASE_TAG_PREFIX}${{ steps.get_version.outputs.value }}"
          tags=$(git ls-remote --tags --refs origin | sed -e 's,^.*refs/tags/,,')
          if printf '%s\n' "$tags" | grep -Fx "${target_tag}" >/dev/null; then
            echo "Error: tag \`${target_tag}\` already exists" >&2
            exit 1
          fi
      - name: Check whether the GitHub Release already exists
        run: |
          tag="${RELEASE_TAG_PREFIX}${{ steps.get_version.outputs.value }}"
          ./.github/tools/assert-no-github-release.sh "$OWNER" "$REPO" "$tag"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.event.repository.owner }}
          REPO: ${{ github.event.repository.name }}
      - name: Verify that the package can be published
        run: cargo publish --dry-run

  check-pull-request-for-non-release:
    name: Check the non-release pull request
    if: ${{ !startsWith(github.head_ref, 'release/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Check the pull request title
        run: |
          case "$PULL_REQUEST_TITLE" in
            "$RELEASE_PULL_REQUEST_TITLE_PREFIX"*)
              echo "Error: the pull request title \`${PULL_REQUEST_TITLE}\` is reserved for release pull requests" >&2
              exit 1
              ;;
          esac
          true
