name: Create Release Pull Request

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Package version"
        required: true

env:
  VERSION: ${{ github.event.inputs.version }}
  TARGET_BRANCH_NAME: "main"
  RELEASE_BRANCH_NAME: "release/${{ github.event.inputs.version }}"
  RELEASE_TAG_NAME: "${{ github.event.inputs.version }}"

concurrency:
  create-release-pull-request

jobs:
  check-target:
    name: Check the target
    runs-on: ubuntu-latest
    steps:
      - name: Check the target type
        run: |
          if [ "${{ github.ref_type }}" = 'tag' ]; then
            echo "Error: tag is not allowed; this workflow only runs on a branch" >&2
            exit 1
          fi
      - name: Check the target branch name
        run: |
          branch_name="${{ github.ref_name }}"
          test "$branch_name" = "$TARGET_BRANCH_NAME" || {
            echo "Error: branch \`${branch_name}\` is not allowed; this workflow only runs on \`${TARGET_BRANCH_NAME}\`" >&2
            exit 1
          }

  verify-version:
    name: Verify the version string
    needs: check-target
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Verify the version string
        run: ./.github/tools/verify-semver.sh "$VERSION"

  check-prerequisites:
    name: Check prerequisites for creating the release pull request
    needs: verify-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: ${{ env.TARGET_BRANCH_NAME }}
      - name: Check whether the version differs from the package version
        run: |
          current_version="$(cargo metadata --format-version=1 --no-deps | jq --raw-output '.packages[0].version')"
          test "$VERSION" != "$current_version" || {
            echo "Error: version string \`${VERSION}\` is the same as the package version" >&2
            exit 1
          }
      - name: Check whether the release branch already exists
        run: |
          branches=$(git branch --list --remotes | sed -e 's,^[[:space:]]*origin/,,')
          if printf '%s\n' "$branches" | grep -Fx "${RELEASE_BRANCH_NAME}" >/dev/null; then
            echo "Error: branch \`${RELEASE_BRANCH_NAME}\` already exists" >&2
            exit 1
          fi
      - name: Check whether the release tag already exists
        run: |
          tags=$(git ls-remote --tags --refs origin | sed -e 's,^.*refs/tags/,,')
          if printf '%s\n' "$tags" | grep -Fx "${RELEASE_TAG_NAME}" >/dev/null; then
            echo "Error: tag \`${RELEASE_TAG_NAME}\` already exists" >&2
            exit 1
          fi
      - name: Check whether the GitHub Release already exists
        run: |
          owner="${GITHUB_REPOSITORY_OWNER}"
          repo="${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}"
          ./.github/tools/assert-no-github-release.sh "$owner" "$repo" "$RELEASE_TAG_NAME"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create-release-pull-request:
    name: Create release pull request
    needs: check-prerequisites
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Install required tools
        run: cargo install cargo-set-version
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: ${{ env.TARGET_BRANCH_NAME }}
      - name: Update the package version
        run: cargo set-version "$VERSION"
      - name: Create a release pull request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Release ${{ github.event.inputs.version }}
          title: Release ${{ github.event.inputs.version }}
          body: |
            This release pull request was created by the workflow `Create Release Pull Request`.
          branch: ${{ env.RELEASE_BRANCH_NAME }}
          base: ${{ env.TARGET_BRANCH_NAME }}
