name: Release

on:
  pull_request:
    branches:
      - main
    types:
      - closed

env:
  TAG_PREFIX: ""

concurrency:
  release

jobs:
  publish-package:
    name: Publish the package to crates.io
    if: >-
      github.event.pull_request.merged == true &&
      startsWith(github.head_ref, 'release/')
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout merged commit
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
      - name: Get a temporary access token to interact with crates.io using trusted publishing
        id: auth
        uses: rust-lang/crates-io-auth-action@v1
      - name: Publish the package
        run: |
          cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}

  create-release-tag:
    name: Create release tag
    if: >-
      github.event.pull_request.merged == true &&
      startsWith(github.head_ref, 'release/')
    needs: publish-package
    permissions:
      contents: write
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout merged commit
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
      - name: Get the release tag name
        id: get_tag_name
        run: |
          version="$(cargo metadata --format-version=1 --no-deps | jq --raw-output '.packages[0].version')"
          echo "value=${TAG_PREFIX}${version}" >> "$GITHUB_OUTPUT"
      - name: Create the release tag
        id: create_tag
        run: |
          git tag "$TAG_NAME"
          git push origin "$TAG_NAME"
        env:
          TAG_NAME: ${{ steps.get_tag_name.outputs.value }}

  create-github-release:
    name: Create GitHub Release
    if: >-
      github.event.pull_request.merged == true &&
      startsWith(github.head_ref, 'release/')
    needs: create-release-tag
    permissions:
      contents: write
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout merged commit
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
      - name: Get the release tag name
        id: get_tag_name
        run: |
          version="$(cargo metadata --format-version=1 --no-deps | jq --raw-output '.packages[0].version')"
          echo "value=${TAG_PREFIX}${version}" >> "$GITHUB_OUTPUT"
      - name: Create the GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.get_tag_name.outputs.value }}
          name: ${{ steps.get_tag_name.outputs.value }}
          generate_release_notes: true
          draft: true
