name: Release

on:
  pull_request:
    branches:
      - main
    types:
      - closed

env:
  TAG_PREFIX: "v"

jobs:
  release:
    name: Release
    if: >-
      github.event.pull_request.merged == true &&
      startsWith(github.head_ref, 'release/')
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout merged commit
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
      - name: Get tag name
        id: get_tag_name
        run: |
          version="$(cargo metadata --format-version=1 --no-deps | jq --raw-output '.packages[0].version')"
          echo "value=${TAG_PREFIX}${version}" >> "$GITHUB_OUTPUT"
      - name: Create release tag
        id: create_tag
        run: |
          git tag "$TAG_NAME"
          git push origin "$TAG_NAME"
        env:
          TAG_NAME: ${{ steps.get_tag_name.outputs.value }}
      - name: Create GitHub release
        id: create_release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.get_tag_name.outputs.value }}
          name: ${{ steps.get_tag_name.outputs.value }}
          generate_release_notes: true
          draft: true
      - name: Delete release tag after release failure
        if: >-
          ${{
            failure() &&
            steps.create_tag.outcome == 'success' &&
            steps.create_release.outcome == 'failure'
          }}
        run: |
          git push origin --delete "$TAG_NAME"
          git tag --delete "$TAG_NAME"
        env:
          TAG_NAME: ${{ steps.get_tag_name.outputs.value }}
